version: '3.11'

services:

  web:
    restart: unless-stopped
    build: ./mountain_pass
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mountain_pass/:/usr/src/app/
    image: mountain_pass
    ports:
      - 8000:8000
    env_file:
      - ./mountain_pass/.env
    depends_on:
      - db

  db:
    # Использование готового образа postgres
    image: postgres
    # Задание переменных окружения для контейнера с postgres
    environment:
      - POSTGRES_DB=mountain_pass
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
     # Задание имени контейнера для сервиса pgdb
    container_name: db
     # Связывание тома с директорией в контейнере для сохранения данных postgres
    volumes:
      - db:/var/lib/postgresql/data/

volumes:
  db: null