version: '3.11'

services:

  redis:
    restart: unless-stopped
    image: redis:latest
    container_name: rd01
    ports:
      - '6379:6379'

  web:
    restart: unless-stopped
    build: ./NewsPaper
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./NewsPaper/:/usr/src/app/
    image: newspaper
    ports:
      - 8000:8000
    env_file:
      - .env
    links:
      - redis
    depends_on:
      - redis

  celery:
    build: ./NewsPaper
    restart: unless-stopped
    container_name: cl01
    command: celery -A NewsPaper worker -l info
    volumes:
      - ./NewsPaper/:/usr/src/app/
      - ./NewsPaper/db.sqlite3:/usr/src/app/
    depends_on:
      - redis
    env_file:
      - .env

  celery-beat:
    build: ./NewsPaper
    restart: unless-stopped
    command: celery -A NewsPaper beat -l info
    volumes:
      - ./NewsPaper/:/usr/src/app/
    depends_on:
      - redis
    env_file:
      - .env