openapi: 3.0.2
info:
  title: 'Some application'
  version: "0.1"
paths:
  /SubmitData/:
    get:
      operationId: Perevallist
      description: 'List of perevals'
      parameters: []
      responses:
        '200':
          content:
            application/json:
            schema:
              type: object
              items:
              $ref: '#/components/schemas/pereval'
          description: ''
      tags:
        - pereval

    post:
      operationId: PerevalCreate
      description: 'Create pereval'
      parameters: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/pereval'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/pereval'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/pereval'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pereval'
          description: Successful operation
        '405':
          description: Invalid input
        '400':
          description: Bad Request
        tags:
          - perevall





components:
  schemas:
    pereval:
      type: object
      title: pereval
      description: Перевал
      properties:
        beautyTitle:
          type: string
          example: перевал
        title:
          type: string
          example: Пхия
        other_titles:
          type: string
          example: Триев
        connect:
          type: string
          example: ''
        author:
          type: object
          $ref: '#/components/schemas/Author'
        coords:
          type: object
          $ref: '#/components/schemas/Coords'
        level:
          type: object
          $ref: '#/components/schemas/Level'
        add_time:
          type: string
          format: timezone
        image:
          type: array
          $ref: '#/components/schemas/Images'
          example: [
                     {"image_name": "вершина 1", "image": "https://klike.net/uploads/posts/2022-11/1667370486_7-8.jpg"},
                     {"image_name": "вершина 2", "image": "https://klike.net/uploads/posts/2022-11/1667370486_7-8.jpg"},
                   ]
        status:
          type: string
          enum:
              - NEW
              - PEN
              - ACC
              - REJ
          default: NEW

    Author:
      type: object
      title: Author
      description: Автор
      properties:
        email:
          type: string
          example: abc@yandex.ru
        fam:
          type: string
          example: Иванов
        name:
          type: string
          example: Иван
        otc:
          type: string
          example: Иванович

        phone:
          type: string
          example: +74951111111


    Coords:
      type: object
      title: Coords
      description: Координаты
      properties:
        latitude:
          type: number
          example: 27.988056
        longitude:
          type: number
          example: 86.925278
        height:
          type: integer
          example: 8848

    Level:
      type: object
      title: Level
      description: Уровень сложности
      properties:
        winter:
          type: string
          enum:
            - NI
            - A1
            - B1
            - A2
            - B2
            - A3
            - B3
        summer:
          type: string
          enum:
            - NI
            - A1
            - B1
            - A2
            - B2
            - A3
            - B3
        autumn:
          type: string
          enum:
            - NI
            - A1
            - B1
            - A2
            - B2
            - A3
            - B3
        spring:
          type: string
          enum:
            - NI
            - A1
            - B1
            - A2
            - B2
            - A3
            - B3

    Images:
      type: object
      title: Images
      description: Фотография перевала
      properties:
        per_image_name:
          type: string
          example: Вершина
        per_image:
          type: string
          format: url
          description: Ссылка на фотографию
