# Generated by Django 4.2.4 on 2023-09-04 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='электронная почта')),
                ('phone', models.CharField(max_length=12, verbose_name='номер телефона')),
                ('fam', models.CharField(max_length=30, verbose_name='фамилия')),
                ('name', models.CharField(max_length=30, verbose_name='имя')),
                ('otc', models.CharField(max_length=30, verbose_name='отчество')),
            ],
        ),
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(max_length=8, verbose_name='широта')),
                ('longitude', models.FloatField(max_length=8, verbose_name='долгота')),
                ('height', models.IntegerField(verbose_name='высота')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(choices=[('NI', 'нет информации'), ('A1', '1А'), ('B1', '1Б'), ('А2', '2А'), ('В2', '2Б'), ('А3', '3А'), ('В3', '3Б')], default='NI', max_length=2, verbose_name='уровень сложности зимой')),
                ('summer', models.CharField(choices=[('NI', 'нет информации'), ('A1', '1А'), ('B1', '1Б'), ('А2', '2А'), ('В2', '2Б'), ('А3', '3А'), ('В3', '3Б')], default='NI', max_length=2, verbose_name='уровень сложности летом')),
                ('autumn', models.CharField(choices=[('NI', 'нет информации'), ('A1', '1А'), ('B1', '1Б'), ('А2', '2А'), ('В2', '2Б'), ('А3', '3А'), ('В3', '3Б')], default='NI', max_length=2, verbose_name='уровень сложности осенью')),
                ('spring', models.CharField(choices=[('NI', 'нет информации'), ('A1', '1А'), ('B1', '1Б'), ('А2', '2А'), ('В2', '2Б'), ('А3', '3А'), ('В3', '3Б')], default='NI', max_length=2, verbose_name='уровень сложности весной')),
            ],
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(choices=[('NI', 'нет информации'), ('PS', 'Перевал'), ('TP', 'Вершина'), ('GL', 'Ледник'), ('IO', 'Объект инфраструктуры'), ('NO', 'Объект природы')], default='NI', max_length=2, verbose_name='тип высоты')),
                ('title', models.TextField(verbose_name='название')),
                ('other_titles', models.TextField(verbose_name='комментарий')),
                ('connect', models.TextField(blank=True, default='', verbose_name='соединение')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NEW', 'новый'), ('PEN', 'в работе'), ('ACC', 'принят'), ('REJ', 'отклонен')], default='NEW', max_length=3, verbose_name='статус')),
                ('spr_activities_types', models.CharField(choices=[('1', 'пешком'), ('2', 'лыжи'), ('3', 'катамаран'), ('4', 'байдарка'), ('5', 'плот'), ('6', 'сплав'), ('7', 'велосипед'), ('8', 'автомобиль'), ('9', 'мотоцикл'), ('10', 'парус'), ('11', 'верхом')], default='1', max_length=2, verbose_name='активность')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pass_base.author', verbose_name='автор')),
                ('coords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pass_base.coords', verbose_name='координаты')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pass_base.level', verbose_name='уровень сложности')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.TextField(verbose_name='комментарий')),
                ('image', models.URLField(blank=True, null=True, verbose_name='фотография')),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pass_base.pereval', verbose_name='перевал')),
            ],
        ),
    ]
